language: node_js  #设置语言

node_js: stable  #设置相应的版本

install:
  - npm install  #安装hexo及插件

before_script:
- git config --global user.name "tiancai.zang"
- git config --global user.email "laidu823@gamil.com"
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script:
  - hexo cl #清除
  - hexo g  #生成
  - hexo d  #部署

after_script:

branches:
  only:
    - master
