language: node_js

node_js: stable

install:
  - npm install

before_script:
- git config --global user.name "tiancai.zang"
- git config --global user.email "laidu823@gamil.com"
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script:
  - hexo cl
  - hexo g
  - hexo d

after_script:

branches:
  only:
    - master

notifications:
  email: true
